# Generated by Django 5.1.7 on 2025-04-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('im', models.CharField(max_length=50, unique=True)),
                ('cin', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('diplome', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('corps', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
            ],
        ),
    ]
