# Generated by Django 5.1.7 on 2025-04-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_date_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='date_debut',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
