# Generated by Django 5.1.7 on 2025-04-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agent_date_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='cin',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='im',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
