# Generated by Django 5.1.7 on 2025-04-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agent_cin_alter_agent_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='qualite',
            field=models.CharField(choices=[('EFA', 'EFA'), ('ELD', 'ELD'), ('E', 'E'), ('Fonctionnaire', 'Fonctionnaire')], default='EFA', max_length=20),
        ),
    ]
