# Generated by Django 5.1.7 on 2025-04-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_qualite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='qualite',
            field=models.CharField(choices=[('EFA', 'EFA'), ('ELD', 'ELD'), ('E', 'E'), ('Fonctionnaire', 'Fonctionnaire')], max_length=20),
        ),
    ]
