# Generated by Django 5.1.7 on 2025-05-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_resetcode_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default=' ', max_length=10),
        ),
    ]
