# Generated by Django 5.1.7 on 2025-05-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agent_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='direction',
            field=models.CharField(choices=[('DPSSE', 'Direction de la Planification Stratégique du Suivi et Evaluation'), ('DIR.COM', 'Direction de la Communication'), ('DRHM', 'Direction des Ressources Humaines du Minisatère'), ('DRTEFOP', 'Direction Régionales du Travail de l Emploi et de la Fonction Publique'), ('DSI', 'Direction du Système d Information'), ('DGT', 'Direction Générale du Travail'), ('DTPDF', 'Direction du Travail et de la Promotion des Droits fondamentaux'), ('DMP', 'Direction de la Migration Professionnelle'), ('DSST', 'Direction de la Sécurité Sociale des Travailleurs'), ('DGPE', 'Direction Générale de la Promotion de l Emploi')], default=' ', max_length=100),
        ),
    ]
