# Generated by Django 5.1.7 on 2025-05-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_alter_agent_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='agent',
            name='qualite',
            field=models.CharField(choices=[('EFA', 'EFA'), ('ELD', 'ELD'), ('E', 'E'), ('Fonctionnaire', 'Fonctionnaire')], default=' ', max_length=20),
        ),
    ]
