# Generated by Django 5.1.7 on 2025-05-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='qualite_initiale',
            field=models.CharField(blank=True, choices=[('EFA', 'EFA'), ('ELD', 'ELD'), ('E', 'E'), ('Fonctionnaire', 'Fonctionnaire')], max_length=20, null=True),
        ),
    ]
