# Generated by Django 5.1.7 on 2025-06-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_agent_qualite_initiale'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=100),
            preserve_default=False,
        ),
    ]
