# Generated by Django 5.1.7 on 2025-06-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_agent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
