# Generated by Django 5.1.7 on 2025-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_remove_agent_signature_dossiersignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='face_descriptor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='mot_de_passe',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='webauthn_credential',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
