# Generated by Django 5.1.7 on 2025-07-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0020_agent_face_descriptor_agent_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='face_descriptor',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='webauthn_credential',
        ),
    ]
