# Generated by Django 5.1.7 on 2025-07-16 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0022_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
