# Generated by Django 5.1.7 on 2025-07-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_alter_message_destinataire_alter_message_expediteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='destinataire',
            field=models.CharField(max_length=100),
        ),
    ]
