# Generated by Django 5.1.7 on 2025-07-16 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0028_agent_utilisateur'),
        ('messagerie', '0003_alter_message_destinataire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='expediteur',
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agent'),
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
