# Generated by Django 5.1.7 on 2025-07-16 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0028_agent_utilisateur'),
        ('messagerie', '0004_remove_message_expediteur_message_expediteur_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='destinataire',
        ),
        migrations.AddField(
            model_name='message',
            name='destinataire_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='message',
            name='destinataire_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='expediteur_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='agents.agent'),
        ),
    ]
