# Generated by Django 5.1.7 on 2025-07-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0005_remove_message_destinataire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date_envoi']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='destinataire_agent',
            new_name='destinataire',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='expediteur_agent',
            new_name='expediteur',
        ),
        migrations.AlterField(
            model_name='message',
            name='destinataire_role',
            field=models.CharField(default=16, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='expediteur_role',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
