# Generated by Django 5.1.7 on 2025-07-16 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0028_agent_utilisateur'),
        ('messagerie', '0006_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='destinataire',
        ),
        migrations.AlterField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agent'),
        ),
    ]
